config/routes.rb
BriefMachine::Application.routes.draw do

  resources :gob_docs
  resources :gob_vars
  resources :ofiles

  resources :complaints do 
    collection do
      get :search
      post :save_assign
      get :assign
      get :mycomplaints
      get :en_tramite
      get :no_asignadas
      get :procedimiento_ordinario
      get :procedimiento_verbal
      get :reabrir_expediente
    end
  end
  
  
  get '/edit_my_account', :to => 'boyaca#edit_my_account'
  get '/ayuda', :to => 'boyaca#ayuda'
  put '/update_my_account', :to => 'boyaca#update_my_account'
  
  
  get '/en_tramite', :to => 'complaints#en_tramite'
  get '/no_asignadas', :to => 'complaints#no_asignadas'
  get '/procedimiento_ordinario', :to => 'complaints#procedimiento_ordinario'
  get '/procedimiento_verbal', :to => 'complaints#procedimiento_verbal'
  get '/estadisticas', :to => 'complaints#estadisticas'
  get '/expedientes_archivados', :to => 'complaints#expedientes_archivados'
  
  get '/admin/users', :to => 'admin#users', :as => :admin_users
  get '/admin/users/:user_id', :to => 'admin#show_user', :as => :admin_show_user
  get '/admin/edit_user/:user_id', :to => 'admin#edit_user', :as => :admin_edit_user
  put '/admin/edit_user/:user_id', to: 'admin#update_user'
  delete '/admin/destroy_user/:user_id', :to => 'admin#destroy_user', :as => :admin_destroy_user
  get '/admin/new_user', :to => 'admin#new_user', :as => :admin_new_user
  post '/admin/new_user', to: 'admin#create_user'
  post '/save_assign', to: 'admin#save_assign', :as => :save_assign

  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_for :users
      

  devise_scope :user do
    root :to => 'complaints#index'
  end

end

app/views/admin/edit_user.html.erb
<h1>Editar usuario</h1>

<%= form_for(@user, url: url_for(:controller => 'admin', :action => 'update_user')) do |f| %>
  
  <div ><label>Roles </label><br />
  <%= f.select(:role_id, @roles.collect{|privilege| [privilege.name.capitalize, privilege.id]}, {:prompt => "Tipo de usuario"}, {:class=>"form-control"}) %></div>
  <br />
  
  <div><label>Nombre </label><br />
  <%= f.text_field :first_name, :class=>"form-control", autofocus: true %></div>

  <br />

  <div><label>Apellidos</label><br />
  <%= f.text_field :last_name , :class=>"form-control" %></div>

	<br />

 

  <div><label>Email</label><br />
  <%= f.email_field :email , :class=>"form-control" %></div>
  
  <br />

 <div><label>Contraseña</label><br />
    <%= f.password_field :password, autocomplete: "off" , :class=>"form-control" %></div>
	
	<br />

  <div><label>Confirmar Contraseña</label><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" , :class=>"form-control" %></div>
	
	<br />

  <div><%= f.submit "Guardar" ,:class=>"buttonregister" %></div>
<% end %>

app/views/admin/new_user.html.erb
<h1>Nuevo Usuario</h1>

<%= form_for(@user, url: url_for(:controller => 'admin', :action => 'create_user')) do |f| %>
  
  <div><%= f.label :first_name %><br />
  <%= f.text_field :first_name, :class=>"form-control", autofocus: true %></div>


  <div ><%= f.label :last_name %><br />
  <%= f.text_field :last_name , :class=>"form-control" %></div>

  <div ><%= f.label :role_id %><br />
  <%= f.select(:role_id, @roles.collect{|privilege| [privilege.name.capitalize, privilege.id]}, {:prompt => "Tipo de usuario"}, {:class=>"form-control"}) %></div>

  <div ><%= f.label :email %><br />
  <%= f.email_field :email, :class=>"form-control" %></div>

  <div ><%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" , :class=>"form-control"  %></div>

  <div ><%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" , :class=>"form-control"  %></div>

  <div><%= f.submit "Crear usuario", :class=>"buttonregister" %></div>
<% end %>

app/views/admin/show_user.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Nombre:</b>
  <%= @user.first_name %> <%= @user.last_name %>
</p>

<p>
  <b>Tipo de usuario:</b>
  <%= @user.role.name %>
</p>

<p>
  <b>Correo:</b>
  <%= @user.email %>
</p>

<p>
  Historial de proccesos 
</p>
<%= link_to 'Atras', admin_users_path %>

app/views/admin/users.html.erb
<h1>Usuarios en el sistema</h1>

<table class="table">
  <tr>
    <th>Nombre</th>
    <th>Email</th>
    <th>Tipo de usuario</th>
	<th>Primera clave</th>
    <th>Opciones</th>
  
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %> <%= user.last_name %></td>
    <td><%= user.email %></td>
    <td><%= user.role.name if user.role %></td>
    <td><%= user.first_password %></td>
    <td>
		
	    <%= link_to admin_edit_user_path(user) do %>
	      <i class="fa fa-pencil"></i>
	    <%end%>
	
		<%= link_to admin_destroy_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } do %>
		  <i class="fa fa-remove"></i>
		<%end%>
		
    </td>
	
  </tr>
<% end %>
</table>

<br />

<%= link_to admin_new_user_path do %>
  <%= image_tag "user-plus.png" %>
  <span>Nuevo usuario</span>
<% end %>