config/routes.rb
BriefMachine::Application.routes.draw do

  resources :gob_docs
  resources :gob_vars
  resources :ofiles

  resources :complaints do 
    collection do
      get :search
      post :save_assign
      get :assign
      get :mycomplaints
      get :en_tramite
      get :no_asignadas
      get :procedimiento_ordinario
      get :procedimiento_verbal
      get :reabrir_expediente
    end
  end
  
  
  get '/edit_my_account', :to => 'boyaca#edit_my_account'
  get '/ayuda', :to => 'boyaca#ayuda'
  put '/update_my_account', :to => 'boyaca#update_my_account'
  
  
  get '/en_tramite', :to => 'complaints#en_tramite'
  get '/no_asignadas', :to => 'complaints#no_asignadas'
  get '/procedimiento_ordinario', :to => 'complaints#procedimiento_ordinario'
  get '/procedimiento_verbal', :to => 'complaints#procedimiento_verbal'
  get '/estadisticas', :to => 'complaints#estadisticas'
  get '/expedientes_archivados', :to => 'complaints#expedientes_archivados'
  
  get '/admin/users', :to => 'admin#users', :as => :admin_users
  get '/admin/users/:user_id', :to => 'admin#show_user', :as => :admin_show_user
  get '/admin/edit_user/:user_id', :to => 'admin#edit_user', :as => :admin_edit_user
  put '/admin/edit_user/:user_id', to: 'admin#update_user'
  delete '/admin/destroy_user/:user_id', :to => 'admin#destroy_user', :as => :admin_destroy_user
  get '/admin/new_user', :to => 'admin#new_user', :as => :admin_new_user
  post '/admin/new_user', to: 'admin#create_user'
  post '/save_assign', to: 'admin#save_assign', :as => :save_assign

  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_for :users
      

  devise_scope :user do
    root :to => 'complaints#index'
  end

end

app/models/ofile.rb
class Ofile < ActiveRecord::Base
  attr_accessible :name, :step
  
  attr_accessible :avatar, :complaint_id
  has_attached_file :avatar
  validates_attachment_content_type :avatar, content_type: /\w/
  validates :avatar_file_name, :presence => true
  
  belongs_to :complaint
  #validates_attachment :image, content_type: { content_type: /\Aimage\/.*\Z/ }
  
end

app/controllers/ofiles_controller.rb
class OfilesController < ApplicationController
  # GET /ofiles
  # GET /ofiles.json
  def index
    @ofiles = Ofile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ofiles }
    end
  end

  # GET /ofiles/1
  # GET /ofiles/1.json
  def show
    @ofile = Ofile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ofile }
    end
  end

  # GET /ofiles/new
  # GET /ofiles/new.json
  def new
    @ofile = Ofile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ofile }
    end
  end

  # GET /ofiles/1/edit
  def edit
    @ofile = Ofile.find(params[:id])
  end

  # POST /ofiles
  # POST /ofiles.json
  def create
    @ofile = Ofile.new(params[:ofile])
    @complaint = @ofile.complaint
    
    puts "ACA STEPS"
    puts params[:step]
    
    
    if params[:step] == "default-title-0"
      @ofile.step = "step0"
      @complaint.step = "step0"
    elsif params[:step] == "default-title-1"
      @ofile.step = "step1"
      @complaint.step = "step1"
    elsif params[:step] == "default-title-2"
      @ofile.step = "step2"
      @complaint.step = "step2"
    elsif params[:step] == "default-title-3"
      @ofile.step = "step3"
      @complaint.step = "step3"
    elsif params[:step] == "default-title-4"
      @ofile.step = "step4"
      @complaint.step = "step4"
    elsif params[:step] == "default-title-5"
      @ofile.step = "step5"
      @complaint.step = "step5"
    elsif params[:step] == "default-title-6"
      @ofile.step = "step6"
      @complaint.step = "step6"
    elsif params[:step] == "default-title-7"
      @ofile.step = "step7"
      @complaint.step = "step7"
    elsif params[:step] == "default-title-8"
      @ofile.step = "step8"
      @complaint.step = "step8"
    elsif params[:step] == "default-title-9"
      @ofile.step = "step9"
      @complaint.step = "step9"
    elsif params[:step] == "default-title-10"
      @ofile.step = "step10"
      @complaint.step = "step10"
    end
    
    @complaint.save
    
    respond_to do |format|
      if @ofile.save
        format.html { redirect_to edit_complaint_path(@complaint), notice: 'Archivo añadido exitosamente' }
        format.json { render json: @complaint, status: :created, location: @complaint }
      else
        format.html { redirect_to edit_complaint_path(@complaint), notice: 'Por favor seleccione un archivo valido' }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ofiles/1
  # PUT /ofiles/1.json
  def update
    @ofile = Ofile.find(params[:id])
    
    
    
    respond_to do |format|
      if @ofile.update_attributes(params[:ofile])
        format.html { redirect_to @ofile, notice: 'Ofile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ofile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ofiles/1
  # DELETE /ofiles/1.json
  def destroy
    @ofile = Ofile.find(params[:id])
    @ofile.destroy

    respond_to do |format|
      format.html { redirect_to ofiles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ofiles_helper.rb
module OfilesHelper
end

app/views/ofiles/_form.html.erb
<%= form_for(@ofile) do |f| %>
  <% if @ofile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ofile.errors.count, "error") %> prohibited this ofile from being saved:</h2>

      <ul>
      <% @ofile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ofiles/edit.html.erb
<h1>Editing ofile</h1>

<%= render 'form' %>

<%= link_to 'Show', @ofile %> |
<%= link_to 'Back', ofiles_path %>

app/views/ofiles/index.html.erb
<h1>Listing ofiles</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ofiles.each do |ofile| %>
  <tr>
    <td><%= ofile.name %></td>
    <td><%= link_to 'Show', ofile %></td>
    <td><%= link_to 'Edit', edit_ofile_path(ofile) %></td>
    <td><%= link_to 'Destroy', ofile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ofile', new_ofile_path %>

app/views/ofiles/new.html.erb
<h1>New ofile</h1>

<%= render 'form' %>

<%= link_to 'Back', ofiles_path %>

app/views/ofiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ofile.name %>
</p>


<%= link_to 'Edit', edit_ofile_path(@ofile) %> |
<%= link_to 'Back', ofiles_path %>