config/routes.rb
BriefMachine::Application.routes.draw do

  resources :gob_docs
  resources :gob_vars
  resources :ofiles

  resources :complaints do 
    collection do
      get :search
      post :save_assign
      get :assign
      get :mycomplaints
      get :en_tramite
      get :no_asignadas
      get :procedimiento_ordinario
      get :procedimiento_verbal
      get :reabrir_expediente
    end
  end
  
  
  get '/edit_my_account', :to => 'boyaca#edit_my_account'
  get '/ayuda', :to => 'boyaca#ayuda'
  put '/update_my_account', :to => 'boyaca#update_my_account'
  
  
  get '/en_tramite', :to => 'complaints#en_tramite'
  get '/no_asignadas', :to => 'complaints#no_asignadas'
  get '/procedimiento_ordinario', :to => 'complaints#procedimiento_ordinario'
  get '/procedimiento_verbal', :to => 'complaints#procedimiento_verbal'
  get '/estadisticas', :to => 'complaints#estadisticas'
  get '/expedientes_archivados', :to => 'complaints#expedientes_archivados'
  
  get '/admin/users', :to => 'admin#users', :as => :admin_users
  get '/admin/users/:user_id', :to => 'admin#show_user', :as => :admin_show_user
  get '/admin/edit_user/:user_id', :to => 'admin#edit_user', :as => :admin_edit_user
  put '/admin/edit_user/:user_id', to: 'admin#update_user'
  delete '/admin/destroy_user/:user_id', :to => 'admin#destroy_user', :as => :admin_destroy_user
  get '/admin/new_user', :to => 'admin#new_user', :as => :admin_new_user
  post '/admin/new_user', to: 'admin#create_user'
  post '/save_assign', to: 'admin#save_assign', :as => :save_assign

  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_for :users
      

  devise_scope :user do
    root :to => 'complaints#index'
  end

end

app/models/gob_var.rb
class GobVar < ActiveRecord::Base
  attr_accessible :meta_key, :meta_value
  
  validates :meta_key, :presence => true
  validates :meta_value, :presence => true
  
  def self.meta(meta_key)
    object = GobVar.where("meta_key = ?",meta_key).first
    if object
      object.try(:meta_value)
    else
      false
    end
  end
  
end

app/controllers/gob_vars_controller.rb
class GobVarsController < ApplicationController
  # GET /gob_vars
  # GET /gob_vars.json
  def index
    @gob_vars = GobVar.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gob_vars }
    end
  end

  # GET /gob_vars/1
  # GET /gob_vars/1.json
  def show
    @gob_var = GobVar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gob_var }
    end
  end

  # GET /gob_vars/new
  # GET /gob_vars/new.json
  def new
    @gob_var = GobVar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gob_var }
    end
  end

  # GET /gob_vars/1/edit
  def edit
    @gob_var = GobVar.find(params[:id])
  end

  # POST /gob_vars
  # POST /gob_vars.json
  def create
    @gob_var = GobVar.new
    
    if params[:meta_value_color] && params[:meta_value_color] != ""
      @gob_var.meta_value = params[:meta_value_color]
    else
      @gob_var.meta_value = params[:gob_var][:meta_value]
    end
    @gob_var.meta_key = params[:gob_var][:meta_key]
    
    respond_to do |format|
      if @gob_var.save
        format.html { redirect_to gob_vars_url, notice: 'Gob var was successfully created.' }
        format.json { render json: @gob_var, status: :created, location: @gob_var }
      else
        format.html { render action: "new" }
        format.json { render json: @gob_var.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gob_vars/1
  # PUT /gob_vars/1.json
  def update
    @gob_var = GobVar.find(params[:id])
    
    if params[:meta_value_color] && params[:meta_value_color] != ""
      @gob_var.meta_value = params[:meta_value_color]
    else
      @gob_var.meta_value = params[:gob_var][:meta_value]
    end
    @gob_var.meta_key = params[:gob_var][:meta_key]
    
    respond_to do |format|
      if @gob_var.save
        format.html { redirect_to gob_vars_url, notice: 'Gob var was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gob_var.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gob_vars/1
  # DELETE /gob_vars/1.json
  def destroy
    @gob_var = GobVar.find(params[:id])
    @gob_var.destroy

    respond_to do |format|
      format.html { redirect_to gob_vars_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/gob_vars_helper.rb
module GobVarsHelper
end

app/views/gob_vars/_form.html.erb
<%= form_for(@gob_var) do |f| %>
  <% if @gob_var.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gob_var.errors.count, "error") %> prohibited this gob_var from being saved:</h2>

      <ul>
      <% @gob_var.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meta_key %><br />
    <%= f.text_field :meta_key %>
  </div>
  
  
  
  
  
  <%if @gob_var.meta_value[0,1] == "#"%>
  
  <div class="field">
    <%= f.label :meta_value %><br />
    <%= f.text_field :meta_value, :value => "" %>
  </div>
  
  <div class="field">
    <%= f.label :meta_color %><br />
    <%= text_field_tag :meta_value_color, @gob_var.meta_value %>
  </div>
  
  <%else%>
  
  <div class="field">
    <%= f.label :meta_value %><br />
    <%= f.text_field :meta_value %>
  </div>
  
  <div class="field">
    <%= f.label :meta_color %><br />
    <%= text_field_tag :meta_value_color  %>
  </div>
  
  <%end%>
  
  
  
  <div class="actions">
    <%= f.submit "Guardar"%>
  </div>
<% end %>

<script>

$( document ).ready(function() {
    $('#meta_value_color').minicolors();
});

</script>

app/views/gob_vars/edit.html.erb
<h1>Editing Registro</h1>

<%= render 'form' %>

<%= link_to 'Show', @gob_var %> |
<%= link_to 'Back', gob_vars_path %>

app/views/gob_vars/index.html.erb
<h1>Registros de configuración</h1>

<table class="table">
  <tr>
    <th>Meta key</th>
    <th>Meta value</th>
    <th>Opciones</th>
  </tr>

<% @gob_vars.each do |gob_var| %>
  <tr>
    <td><%= gob_var.meta_key %></td>
    <td>
		<%if gob_var.meta_value[0,1] == "#"%>
		  <div class="cuadrado" style= "background: <%=gob_var.meta_value%>"></div>
		<%else%>
		  <%= gob_var.meta_value %>
		<%end%>	
	</td>
    <td>
	
    <%= link_to edit_gob_var_path(gob_var) do %>
      <i class="fa fa-pencil"></i>
    <%end%>
	
	<%= link_to gob_var, method: :delete, data: { confirm: 'Are you sure?' } do %>
	  <i class="fa fa-remove"></i>
	<%end%>
    </td>
	
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo Registro', new_gob_var_path %>

app/views/gob_vars/new.html.erb
<h1>Nuevo Registro De Configuración</h1>

<%= form_for(@gob_var) do |f| %>
  <% if @gob_var.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gob_var.errors.count, "error") %> prohibited this gob_var from being saved:</h2>

      <ul>
      <% @gob_var.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meta_key %><br />
    <%= f.text_field :meta_key %>
  </div>
  
  
  
  <div class="field">
    <%= f.label :meta_value %><br />
    <%= f.text_field :meta_value %>
  </div>
  
  <div class="field">
    <%= f.label :meta_color %><br />
    <%= text_field_tag :meta_value_color %>
  </div>
  
  
  
  <div class="actions">
    <%= f.submit "Guardar"%>
  </div>
<% end %>

<script>

$( document ).ready(function() {
    $('#meta_value_color').minicolors();
});

</script>


<%= link_to 'Back', gob_vars_path %>

app/views/gob_vars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Meta key:</b>
  <%= @gob_var.meta_key %>
</p>

<p>
  <b>Meta value:</b>
  <%= @gob_var.meta_value %>
</p>


<%= link_to 'Edit', edit_gob_var_path(@gob_var) %> |
<%= link_to 'Back', gob_vars_path %>