config/routes.rb
BriefMachine::Application.routes.draw do

  resources :gob_docs
  resources :gob_vars
  resources :ofiles

  resources :complaints do 
    collection do
      get :search
      post :save_assign
      get :assign
      get :mycomplaints
      get :en_tramite
      get :no_asignadas
      get :procedimiento_ordinario
      get :procedimiento_verbal
      get :reabrir_expediente
    end
  end
  
  
  get '/edit_my_account', :to => 'boyaca#edit_my_account'
  get '/ayuda', :to => 'boyaca#ayuda'
  put '/update_my_account', :to => 'boyaca#update_my_account'
  
  
  get '/en_tramite', :to => 'complaints#en_tramite'
  get '/no_asignadas', :to => 'complaints#no_asignadas'
  get '/procedimiento_ordinario', :to => 'complaints#procedimiento_ordinario'
  get '/procedimiento_verbal', :to => 'complaints#procedimiento_verbal'
  get '/estadisticas', :to => 'complaints#estadisticas'
  get '/expedientes_archivados', :to => 'complaints#expedientes_archivados'
  
  get '/admin/users', :to => 'admin#users', :as => :admin_users
  get '/admin/users/:user_id', :to => 'admin#show_user', :as => :admin_show_user
  get '/admin/edit_user/:user_id', :to => 'admin#edit_user', :as => :admin_edit_user
  put '/admin/edit_user/:user_id', to: 'admin#update_user'
  delete '/admin/destroy_user/:user_id', :to => 'admin#destroy_user', :as => :admin_destroy_user
  get '/admin/new_user', :to => 'admin#new_user', :as => :admin_new_user
  post '/admin/new_user', to: 'admin#create_user'
  post '/save_assign', to: 'admin#save_assign', :as => :save_assign

  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_for :users
      

  devise_scope :user do
    root :to => 'complaints#index'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Gobernación de Boyaca. Plataforma de Control Interno">
    <meta name="author" content="Ozone Group">
    <meta name="keyword" content="Gobernación de Boyaca. Plataforma de Control Interno">
    <link rel="shortcut icon" href="/favicon.png">

    <title>Gobernación de Boyaca. Plataforma de Control Interno</title>
    <%= stylesheet_link_tag "application", :media => "all" %>

	<%= csrf_meta_tags %>
	
 <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
 <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
 <script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
	
</head>

<body id="container" class = "font-awesome">	
	<% if user_signed_in? %>
	<header class="header white-bg">
		<div class="sidebar-toggle-box">
			<div data-original-title="Toggle Navigation" data-placement="right" class="icon-reorder glyphicon glyphicon-align-justify"></div>
		</div>
		<!--logo start-->
		<%= link_to "/", class: "logo" do %>
			<%= image_tag "nuevologo.png" %>
		<% end %>
		<!--logo end-->
		<div class="top-nav ">
			<!--search & user info start-->
			<ul class="nav pull-right top-menu">
				<!-- user login dropdown start-->
				<li class="dropdown">
					<a data-toggle="dropdown" class="dropdown-toggle" href="#">
						<%= image_tag "avatar-mini.jpg" %> 
						<span class="username"><%= current_user.first_name %> <%= current_user.last_name %></span>
						
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu extended logout">
						<div class="log-arrow-up"></div>
						
						<li style="text-align: center;margin: 0 auto;width: 100%;">
						  <a><i class="icon-pencil"></i> <%=current_user.get_role.upcase%></a>
						</li>
						
						<li style="text-align: center;margin: 0 auto;width: 100%;">
							<%= link_to edit_user_registration_path do %>
								<i class="icon-pencil"></i> EDITAR CUENTA
							<% end %>
						</li>
						<li>
							<%= link_to destroy_user_session_path, method: :delete do %>
								<i class="icon-key"></i> Cerrar sesión
							<% end %>
						</li>
					</ul>
				</li>
				<!-- user login dropdown end -->
			</ul>
			<!--search & user info end-->
		</div>
	</header>  
	<aside>
		
		<div id="sidebar"  class="nav-collapse ">
			<!-- sidebar menu start-->
			<ul class="sidebar-menu">
				<br>
				<li>
					<%= link_to "/" do %>
						<i><%= image_tag "briefcase.png", :style => "width: 25px;height: 25px;" %></i>
						<span>Expedientes</span>
					<% end %>
					<%= link_to "/complaints/new" do %>
						<i><%= image_tag "pencil.png", :style => "width: 25px;height: 25px;" %></i>
						<span>Nuevo Expediente</span>
					<% end %>
				</li>	
	
				
				<% if current_user.admin?%>
					<li>
						<%= link_to admin_users_path do %>
							<%= image_tag "userw.png", :style => "width: 25px;height: 25px;" %>
							<span>Usuarios</span>
						<% end %>
					</li>
					
					<li>
						<%= link_to gob_docs_path do %>
							<%= image_tag "floppy-disk.png", :style => "width: 25px;height: 25px;" %>
							<span>Migrar datos</span>
						<% end %>
					</li>
					
					<li>
						<%= link_to gob_vars_path do %>
							<%= image_tag "cloud-upload.png", :style => "width: 25px;height: 25px;" %>
							<span>Configuración</span>
						<% end %>
					</li>
					
				<% end %>
				
				<li>
				<%= link_to "/ayuda.pdf" do %>
					<i><%= image_tag "attachment.png", :style => "width: 25px;height: 25px;" %></i>
					<span>Ayuda</span>
				<% end %>
			</li>
				
			</ul>
			<!-- sidebar menu end-->
		</div>
	</aside>

	<section id="main-content">
		<section class="wrapper">
			<%= yield %>
		</section>
	</section>
	<% else %>
		<%= yield %>
	<% end %>
	
	
	
	<%= javascript_include_tag "application" %>
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
	<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
	
    <%= yield :javascript %>
	
	
    
    <script src="http://cdnjs.cloudflare.com/ajax/libs/prettify/r224/prettify.min.js"></script> 
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/prettify/r224/prettify.min.css">
    

	<% flash.each do |type, message| %> 
	<script type="text/javascript">
		$(document).ready(function () {
			var unique_id = $.gritter.add({
				text: "<%= message %>",
				sticky: false,
				time: 4000,
				class_name: 'my-sticky-class'
			});
			return false;
		});
	</script>
	<%end%>
		
		<%= yield :footer %>
		<div id="fb-root"></div>
	</body>


</html>